###
POST {{host}}/v1/api/deliveries/init
Content-Type: application/json

###
POST {{host}}/v1/api/deliveries/action
Content-Type: application/json

{
  "id": "6",
  "deliveryState": "WAIT_ALLOCATE",
  "deliveryDistrict": "SONG_PA"
}

###
POST {{host}}/v1/api/deliveries/action
Content-Type: application/json

{
  "id": "6",
  "deliveryState": "COMPLETE_ALLOCATE",
  "deliveryDistrict": "SONG_PA"
}

###
POST {{host}}/v1/api/deliveries/action
Content-Type: application/json

{
  "id": "6",
  "deliveryState": "COMPLETE_PICKUP",
  "deliveryDistrict": "SONG_PA"
}

###
POST {{host}}/v1/api/deliveries/action
Content-Type: application/json

{
  "id": "5",
  "deliveryState": "COMPLETE_DELIVERY",
  "deliveryDistrict": "SONG_PA"
}

###
GET {{host}}/v1/api/deliveries/count?localDate=2022-09-06&deliveryDistrict=SONG_PA&deliveryState=COMPLETE_DELIVERY
Content-Type: application/json

###
GET {{host}}/v1/api/deliveries/count/state?localDate=2022-09-07&deliveryState=WAIT_ALLOCATE
Content-Type: application/json
